### ISSUE TITLE
Missing Typescript support

### ISSUE THREAD

**Issue by madhavisolanki** [ayush3160/BlogWeb#1]
As per our requirement you need to submit the project in typescript. Let me know if I'm missing any branch.

**Comment by ayush3160** [comment]
I have created the project in Javascript as I am comfortable in that and I am learning typescript as well. Any critique or concern is welcome.
I am a fast paced learner and will port on typescript soon.

**Comment by madhavisolanki** [comment]
You can redo this project in typescript provided you have time and we will circle back to you.

**Comment by ayush3160** [comment]
It was taking very much time to change the whole code. So I have created another project in typescript-react it is a Quiz application which shows different questions with four options and user can choose any one option and application validates the answer by red color for wrong and green color for right. 
At last it shows the score of the user. It also has the timer functionality.
I have created another private repo - https://github.com/ayush3160/quiz-typescript and have added you as the collabrator.
I request you to kindly accept this . I look forward to hearing from you
